services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fastapi
      - appwrite

  fastapi:
    build: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  appwrite:
    image: appwrite/appwrite:1.5.6
    container_name: appwrite
    ports:
      - "8080:80"
    environment:
      - _APP_ENV=production
      - _APP_OPENSSL_KEY_V1=2b7f8e1c9d4a5e6f7b8c0d1e2f3a4b5c
      - _APP_DOMAIN=auth.pwy.rectbot.tech
      - _APP_DOMAIN_TARGET=auth.pwy.rectbot.tech
      - _APP_REDIS_HOST=appwrite-redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=appwrite-mariadb
      - _APP_DB_USER=user
      - _APP_DB_PASS=password
      - _APP_DB_SCHEMA=appwrite
      - _APP_OPTIONS_REALTIME=enabled
      - _APP_CONSOLE_WHITELIST_ROOT=disabled
      - _APP_OPTIONS_REALTIME=enabled
      - _APP_CONSOLE_WHITELIST_ROOT=disabled
    depends_on:
      - appwrite-mariadb
      - appwrite-redis


  appwrite-mariadb:
    image: mariadb:10.7
    container_name: appwrite-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - appwrite-mariadb-data:/var/lib/mysql
    restart: unless-stopped

  appwrite-redis:
    image: redis:7.0-alpine
    container_name: appwrite-redis
    volumes:
      - appwrite-redis-data:/data
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  appwrite-mariadb-data:
  appwrite-redis-data:
