#!/bin/bash

echo "🔧 GitHub Secrets 設定修正ガイド"
echo "=================================================="
echo ""
echo "問題: DISCORD_REDIRECT_URI が dash.rectbot.tech になっている可能性"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 1: GitHub Secrets を確認"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 以下にアクセス:"
echo "   https://github.com/PK-2736/rectbot/settings/secrets/actions"
echo ""
echo "2. 'DISCORD_REDIRECT_URI' の値を確認"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 2: 正しい値に修正"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "もし以下のような値になっていたら修正が必要:"
echo ""
echo "❌ 間違い:"
echo "   https://dash.rectbot.tech/api/discord/callback"
echo "   https://dash.rectbot.tech/"
echo "   http://api.rectbot.tech/api/discord/callback"
echo ""
echo "✅ 正しい値:"
echo "   https://api.rectbot.tech/api/discord/callback"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 3: 修正手順"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. GitHub Secrets ページで 'DISCORD_REDIRECT_URI' をクリック"
echo "2. 'Update secret' をクリック"
echo "3. 以下の値を正確にコピー&ペースト:"
echo ""
echo "   https://api.rectbot.tech/api/discord/callback"
echo ""
echo "4. 'Update secret' ボタンをクリック"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 4: 再デプロイ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "修正後、以下のコマンドで再デプロイ:"
echo ""
echo "  cd /workspaces/rectbot"
echo "  git add ."
echo "  git commit -m 'Trigger redeploy for OAuth fix'"
echo "  git push origin main"
echo ""
echo "または、GitHub Actions ページで手動再実行:"
echo "  https://github.com/PK-2736/rectbot/actions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 5: デプロイログを確認"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "GitHub Actions のログで以下を確認:"
echo ""
echo "  NEXT_PUBLIC_DISCORD_REDIRECT_URI: SET"
echo ""
echo "値が 'SET' と表示されていればOK"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 6: テスト"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 新しいシークレットウィンドウを開く"
echo "2. https://dash.rectbot.tech にアクセス"
echo "3. 「Discordでログイン」をクリック"
echo "4. Discord認証画面のURLバーを確認:"
echo ""
echo "   ✅ 正しい:"
echo "   redirect_uri=https%3A%2F%2Fapi.rectbot.tech%2Fapi%2Fdiscord%2Fcallback"
echo ""
echo "   ❌ 間違い:"
echo "   redirect_uri=https%3A%2F%2Fdash.rectbot.tech%..."
echo ""
echo "=================================================="
