#!/bin/bash

echo "=========================================="
echo "🔐 必須Secretsの設定手順"
echo "=========================================="
echo ""
echo "以下のGitHub Secretsが**設定されていません**:"
echo ""
echo "1. DISCORD_CLIENT_SECRET"
echo "   取得方法: https://discord.com/developers/applications/1048950201974542477/oauth2"
echo "   → Client information → Reset Secret をクリック"
echo "   → 表示されたSecretをコピー（二度と表示されないので注意！）"
echo ""
echo "2. JWT_SECRET"
echo "   値: T/JxEeeJZZ0ywZTnropyM/DWHtwy2b/F0eSgSrHqSUM="
echo ""
echo "3. SUPABASE_SERVICE_ROLE_KEY"
echo "   取得方法: Supabase Dashboard → Project Settings → API"
echo "   → service_role key (secret) をコピー"
echo ""
echo "4. SERVICE_TOKEN"
echo "   生成: openssl rand -base64 32"
echo "   または任意のランダムな文字列"
echo ""
echo "=========================================="
echo "📋 設定URL"
echo "=========================================="
echo ""
echo "https://github.com/PK-2736/rectbot/settings/secrets/actions"
echo ""
echo "各Secretを「New repository secret」から追加してください。"
echo ""
echo "=========================================="
echo "🧪 現在のWorker環境変数"
echo "=========================================="
echo ""
echo "設定済み:"
echo "  ✅ DISCORD_CLIENT_ID"
echo "  ✅ DISCORD_REDIRECT_URI"
echo "  ✅ SUPABASE_URL"
echo "  ✅ VPS_EXPRESS_URL"
echo "  ✅ ADMIN_DISCORD_ID"
echo ""
echo "未設定（これが認証エラーの原因）:"
echo "  ❌ DISCORD_CLIENT_SECRET"
echo "  ❌ JWT_SECRET"
echo "  ❌ SUPABASE_SERVICE_ROLE_KEY"
echo "  ❌ SERVICE_TOKEN"
echo ""
echo "=========================================="
echo "🚀 次のステップ"
echo "=========================================="
echo ""
echo "1. 上記のURLにアクセス"
echo "2. 4つのSecretを追加"
echo "3. git push でWorkerを再デプロイ"
echo "4. デプロイログで以下が表示されることを確認:"
echo "   Registering DISCORD_CLIENT_SECRET"
echo "   Registering JWT_SECRET"
echo "   Registering SUPABASE_SERVICE_ROLE_KEY"
echo "   Registering SERVICE_TOKEN"
echo ""
