http:
  routers:
    frontend:
      rule: "Host(`pwy.rectbot.tech`)"
      service: frontend-external
      entrypoints:
        - websecure
      tls:
        certResolver: letsencrypt
    appwrite-console:
      rule: "Host(`auth.pwy.rectbot.tech`)"
      service: appwrite
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    frontend-external:
      loadBalancer:
        servers:
          - url: "https://<外部フロントエンドのURL>"
    appwrite:
      loadBalancer:
        servers:
          - url: "http://appwrite:80"
