version: '3.8'
services:
  bot:
    build: ../bot
    env_file:
      - ../bot/config.env
    restart: unless-stopped
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
  backend:
    build: ../backend
    restart: unless-stopped
