<?php

// ...既存のコード...
// 101行目付近
if (!is_null($needle) && str_ends_with($haystack, $needle)) {
    // ...既存の処理...
}
// ...既存のコード...
// 578行目付近
if (!is_null($needle) && str_ends_with($haystack, $needle)) {
    // ...既存の処理...
}
// ...既存のコード...
