services:
  fastapi:
    build:
      context: ../backend
    restart: always
    expose:
      - "8080"
    networks:
      - backend

  appwrite:
    image: appwrite/appwrite:1.4.14
    container_name: appwrite
    restart: always
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=production
      # 64 hex (32 bytes) 以上の強ランダム値に必ず置換 (例: 128 hex)
      - _APP_OPENSSL_KEY_V1=91c6c15ebe56ea5822953bd9d179007077acd4357459d6ddc315ad01d993d65c
      - _APP_DOMAIN=auth.pwy.rectbot.tech
      - _APP_DOMAIN_TARGET=auth.pwy.rectbot.tech
      - _APP_CONSOLE_DOMAIN=auth.pwy.rectbot.tech
      - _APP_DB_HOST=mariadb
      - _APP_DB_USER=appwrite
      - _APP_DB_PASS=appwrite-pass
      - _APP_DB_SCHEMA=appwrite
      - _APP_REDIS_HOST=redis
      - _APP_LOGGING_CONFIG={"default":"debug"}
      # ログを internal に一時変更 (問題解決後 disabled に戻す)
      - _APP_LOGGING_PROVIDER=internal
      - _APP_CONSOLE_WHITELIST_ROOT=disabled
      # 開発中: HTTPS 強制と abuse 検知無効 (本番で再検討)
      - _APP_OPTIONS_FORCE_HTTPS=enabled
      - _APP_OPTIONS_ABUSE=disabled
      # 利用統計オフ (任意)
      - _APP_USAGE_STATS=disabled

    volumes:
      - appwrite-storage:/storage
    networks:
      - backend

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=appwrite
      - MYSQL_PASSWORD=appwrite-pass
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: gateway-nginx
    restart: always
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./infra/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/html:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./infra/nginx/logs:/var/log/nginx
    depends_on:
      - fastapi
      - appwrite
    networks:
      - backend

volumes:
  appwrite-storage:
  mariadb-data:

networks:
  backend:
    driver: bridge