name: Deploy to Cloudflare Pages
on:

  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      
  workflow_dispatch:

jobs:
  cloudflare-pages-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/dashboard/package-lock.json'
      - name: Install dependencies for Dashboard
        run: |
          cd frontend/dashboard
          npm ci
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Build Dashboard
        env:
          NEXT_PUBLIC_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          NEXT_PUBLIC_DISCORD_REDIRECT_URI: ${{ secrets.DISCORD_REDIRECT_URI }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_ADMIN_IDS: ${{ secrets.ADMIN_DISCORD_ID }}
        run: |
          cd frontend/dashboard
          
          # 環境変数のデバッグ出力（値は表示しない）
          echo "=== Environment Variables Check ==="
          echo "NEXT_PUBLIC_DISCORD_CLIENT_ID: ${NEXT_PUBLIC_DISCORD_CLIENT_ID:+SET}" 
          echo "NEXT_PUBLIC_DISCORD_REDIRECT_URI: ${NEXT_PUBLIC_DISCORD_REDIRECT_URI:+SET}"
          echo "NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:+SET}"
          echo "NEXT_PUBLIC_ADMIN_IDS: ${NEXT_PUBLIC_ADMIN_IDS:+SET}"
          echo "==================================="
          
          npm run build
          npm run export
      - name: Deploy Dashboard to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd frontend/dashboard
          # プロジェクトを作成（存在しない場合のみ）
          echo "Creating Dashboard project if it doesn't exist..."
          wrangler pages project create rectbot-dashboard --production-branch=main --compatibility-date=2024-09-18 2>/dev/null || echo "Project already exists"
          
          # デプロイ実行（環境変数はビルド時に既に埋め込み済み）
          echo "Deploying Dashboard to Pages..."
          wrangler pages deploy ./out --project-name=rectbot-dashboard \
            --env production \
            --branch main
      - name: Install Bun for Astro
        run: curl -fsSL https://bun.sh/install | bash
        shell: bash
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies for Astro
        run: |
          cd frontend/astro
          bun install
      - name: Build Astro frontend
        run: |
          cd frontend/astro
          bun run build
      - name: Deploy Astro to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd frontend/astro
          # プロジェクトを作成（存在しない場合のみ）
          echo "Creating Astro project if it doesn't exist..."
          wrangler pages project create rectbot --production-branch=main --compatibility-date=2024-09-18 2>/dev/null || echo "Project already exists or creation failed"
          
          # デプロイ実行
          echo "Deploying Astro to Pages..."
          wrangler pages deploy ./dist --project-name=rectbot
