name: Deploy to Cloudflare Workers
on:
  push:
    branches:
      - "main"
    paths:
      - "backend/**"
      
  workflow_dispatch:

jobs:
  cloudflare-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
        shell: bash
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies
        run: |
          cd backend
          bun install
      - name: Install Wrangler
        run: cd backend && npm install wrangler
      - name: Deploy to Cloudflare Workers
        run: |
          cd backend
          npx wrangler deploy
