name: Deploy to Cloudflare Pages
on:

  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      
  workflow_dispatch:

jobs:
  cloudflare-pages-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
        shell: bash
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies
        run: |
          cd frontend
          bun install
      - name: Build frontend
        run: |
          cd frontend
          bun run build
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
        run: |
          cd frontend
          npx wrangler pages deploy ./build --project-name=rectbot-frontend
