name: Deploy to Cloudflare Pages
on:

  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      
  workflow_dispatch:

jobs:
  cloudflare-pages-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/dashboard/package-lock.json'
      - name: Install dependencies for Dashboard
        run: |
          cd frontend/dashboard
          npm install
      - name: Install dependencies
        run: |
          cd frontend/dashboard
          npm ci
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Build Dashboard
        env:
          NEXT_PUBLIC_DISCORD_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_DISCORD_CLIENT_ID }}
          NEXT_PUBLIC_DISCORD_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_DISCORD_REDIRECT_URI }}
          NEXT_PUBLIC_BACKEND_API_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          cd frontend/dashboard
          npm run build
      - name: Deploy Dashboard to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: rectbot-dashboard
          directory: frontend/dashboard/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Bun for Astro
        run: curl -fsSL https://bun.sh/install | bash
        shell: bash
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies for Astro
        run: |
          cd frontend/astro
          bun install
      - name: Build Astro frontend
        run: |
          cd frontend/astro
          bun run build
      - name: Deploy Astro to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
        run: |
          cd frontend/astro
          npx wrangler pages deploy ./dist --project-name=rectbot-frontend
